#!/usr/bin/env python3

import rospy
import sys

import time

from hyper_rail.srv import InterfaceService, InterfaceServiceRequest, InterfaceServiceResponse


def path_client(x):
    rospy.wait_for_service('interface_service')
    try:
        message = rospy.ServiceProxy('interface_service', InterfaceService)
        resp1 = message(x)
        return resp1.path_response
    except rospy.ServiceException as e:
        print("Service call failed: %s"%e)

def usage():
    return "%s [program id placeholder]"%sys.argv[0]

if __name__ == "__main__":
    if len(sys.argv) == 2:
        x = str(sys.argv[1])
    else:
        print(usage())
        sys.exit(1)
    print("Requesting %s"%(x))
    print("received: %s"%(path_client(x)))
    # print("%s + %s = %s"%(x, y, add_two_ints_client(x, y)))