#!/usr/bin/env python3

# This can be used for the basis of the camera node. Currently just hosts the
# camera service.

import rospy
import time

from communication.camera_executor import Micasense
from hyper_rail.srv import SensorService, SensorServiceRequest, SensorServiceResponse

from communication.constants import DEFAULT_CAMERA_HOST, IMAGE_PATH

#Called when service receives new request
def receive_command(req: SensorServiceRequest):
    print("* Camera Mock\n * received action:", req.action)
    Cam = Micasense(IMAGE_PATH, req.program_run_id, req.run_waypoint_id, [1, 1, 1, 1, 1])
    captured = Cam.capture_image()
    # req should be of class : SensorService Request and has types: 
    # uint32 program_run_id | uint32 run_waypoint_id | string action 
    if captured:
        Cam.transfer_to_local_storage()
        print("Images captured successfully")
    else:
        print("Error: Image not capture")
    return("camera success")


def init_node():
    """Create the ros node and basic functionality"""
    rospy.init_node("CameraMock")

    # Sleep once per second. Just keeping the node alive
    publish_rate = rospy.Rate(1)

    # Service to receive camera commands
    service = rospy.Service("camera_service", SensorService, handler=receive_command)

    # Inform the user that the node and service have been started successfully
    rospy.loginfo(f"{rospy.get_name()}: serial connection established...") 

    while not rospy.is_shutdown():
        publish_rate.sleep()

if __name__ == "__main__":
    init_node()