#!/usr/bin/env python3

# Mock endpoint for testing GreenhouseSensorReadings topic
# Publishes a random number between [-40 : 125], the range in celsius of the SHT-31, to the greenhouse_sensor_readings topic

import rospy
import time
import random

from hyper_rail.msg import GreenhouseSensorReadings

def rand_temp():
    num = random.uniform(-40.00, 125.00)
    return num

def init_node():
    random.seed(0)
    """Create the ros node and basic functionality"""
    rospy.init_node("SensorMock")

    # Sleep once per second. This may not actually be necessary
    publish_rate = rospy.Rate(1)
    publisher = rospy.Publisher("greenhouse_sensor_readings", GreenhouseSensorReadings, queue_size=1000)

    # publish once per second
    publish_rate = rospy.Rate(1)

    # Inform the user that the node and service have been started successfully
    rospy.loginfo(f"{rospy.get_name()}: serial connection established...") 

    while not rospy.is_shutdown():
        temperature = random.uniform(-40.00, 125.00)
        #print(temperature)
        publisher.publish(
            start_read_time = time.time(),
            temperature=temperature,
            end_read_time = time.time()
            )
        publish_rate.sleep()

if __name__ == "__main__":
    init_node()