#!/usr/bin/env python3

import rospy

from hyper_rail.msg import GreenhouseSensorReadings
from serial_comms.eGreenhouse_Driver import GreenhouseDriver
from communication.constants import GREENHOUSE_SENSOR_SERIAL

def init_node():
    """Create the ros node an add basic topic functionality (Technical functions are stored in an src file)"""
    rospy.init_node("eGreenhouseParser")

    # Publisher object to maintain the sensor output topic
    publisher = rospy.Publisher("greenhouse_sensor_readings", GreenhouseSensorReadings)

    # Pull data from sensor end effector at 111ms intervals
    publish_rate = rospy.Rate(9)

    # TODO: Channge USB port as it will likely be different on the actual device
    # Create a new driver object with the baudrate and location pulled from the constants file
    greenHouseController = GreenhouseDriver(GREENHOUSE_SENSOR_SERIAL[0], GREENHOUSE_SENSOR_SERIAL[1])

    # Inform the user that the node and service have been started successfully
    rospy.loginfo(f"{rospy.get_name()}: serial connection established...")

    # Wait until ros is stopped
    while not rospy.is_shutdown():
        # Publish the sensor readings to the topic
        publisher.publish(greenHouseController.poll_data())
        
        # Maintain the correct interval for pulling data
        publish_rate.sleep()


if __name__ == "__main__":
    """Called when the node is started"""
    init_node()
