# Structure for packets sent from the Program Node to the Motion Node

int16 x       # x coordinate in mm
int16 y       # y coordinate in mm

---

string status # location status, should include or change this to an int?